import { hashString } from './rng'

export type Category = 'history' | 'science' | 'tech' | 'culture' | 'sport' | 'explore'

export interface HistEvent {
  id: string
  /** Negative for BC. */
  year: number
  text: string
  cat: Category
  /** Date is traditional or approximate, shown as "c. 2560 BC". */
  approx?: boolean
}

export const CATEGORY_ICON: Record<Category, string> = {
  history: '🏛️',
  science: '🔬',
  tech: '💻',
  culture: '🎬',
  sport: '🏅',
  explore: '🧭',
}

type Row = [year: number, cat: Category, text: string, approx?: boolean]

// Keep entries well known and their dates uncontroversial: a puzzle that marks a
// player wrong on a disputed date is the fastest way to lose them.
//
// Daily puzzles are drawn from this list, so adding or removing a row reshuffles
// every puzzle from that deploy on. Ship data changes rather than tweaking it daily.
const ROWS: Row[] = [
  [-2560, 'history', 'The Great Pyramid of Giza is completed', true],
  [-776, 'sport', 'The first recorded Olympic Games are held in Greece', true],
  [-753, 'history', 'Rome is founded, according to legend', true],
  [-490, 'history', 'The Battle of Marathon', true],
  [-336, 'history', 'Alexander the Great becomes king of Macedon'],
  [-221, 'history', 'Qin Shi Huang unifies China'],
  [-44, 'history', 'Julius Caesar is assassinated'],
  [-27, 'history', 'Augustus becomes the first Roman emperor'],
  [79, 'history', 'Mount Vesuvius buries Pompeii'],
  [80, 'culture', 'The Colosseum opens in Rome'],
  [122, 'history', "Construction of Hadrian's Wall begins"],
  [476, 'history', 'The Western Roman Empire falls'],
  [537, 'culture', 'The Hagia Sophia is completed in Constantinople'],
  [622, 'history', 'Muhammad migrates from Mecca to Medina (the Hijra)'],
  [793, 'history', 'Vikings raid the monastery at Lindisfarne'],
  [800, 'history', 'Charlemagne is crowned emperor'],
  [1066, 'history', 'The Battle of Hastings'],
  [1096, 'history', 'The First Crusade begins'],
  [1206, 'history', 'Genghis Khan is proclaimed ruler of the Mongols'],
  [1215, 'history', 'The Magna Carta is sealed'],
  [1271, 'explore', 'Marco Polo sets out for Asia'],
  [1347, 'history', 'The Black Death reaches Europe'],
  [1440, 'tech', "Gutenberg develops his printing press", true],
  [1453, 'history', 'Constantinople falls to the Ottomans'],
  [1492, 'explore', 'Columbus reaches the Americas'],
  [1503, 'culture', 'Leonardo da Vinci begins painting the Mona Lisa', true],
  [1517, 'history', 'Martin Luther posts his 95 Theses'],
  [1519, 'explore', "Magellan's expedition sets sail to circle the globe"],
  [1543, 'science', 'Copernicus publishes his Sun-centred model of the universe'],
  [1564, 'culture', 'William Shakespeare is born'],
  [1588, 'history', 'The Spanish Armada is defeated'],
  [1605, 'culture', 'The first part of Don Quixote is published'],
  [1610, 'science', "Galileo discovers Jupiter's four largest moons"],
  [1620, 'explore', 'The Mayflower reaches Plymouth'],
  [1632, 'culture', 'Construction of the Taj Mahal begins'],
  [1666, 'history', 'The Great Fire of London'],
  [1687, 'science', "Newton publishes the Principia, with his laws of motion"],
  [1707, 'history', 'England and Scotland unite as Great Britain'],
  [1752, 'science', "Benjamin Franklin's kite experiment"],
  [1769, 'tech', "James Watt patents his improved steam engine"],
  [1776, 'history', 'The US Declaration of Independence is signed'],
  [1788, 'explore', 'The First Fleet arrives in Australia'],
  [1789, 'history', 'The storming of the Bastille'],
  [1796, 'science', 'Edward Jenner tests the first vaccine, against smallpox'],
  [1799, 'science', 'The Rosetta Stone is discovered'],
  [1804, 'history', 'Napoleon crowns himself Emperor of the French'],
  [1813, 'culture', 'Pride and Prejudice is published'],
  [1815, 'history', 'The Battle of Waterloo'],
  [1818, 'culture', 'Frankenstein is published'],
  [1825, 'tech', 'The first public steam railway opens, Stockton to Darlington'],
  [1826, 'tech', 'The oldest surviving photograph is taken', true],
  [1837, 'history', 'Victoria becomes Queen'],
  [1844, 'tech', 'The first long-distance telegraph message: "What hath God wrought"'],
  [1848, 'history', 'The California Gold Rush begins'],
  [1851, 'culture', "London's Great Exhibition opens in the Crystal Palace"],
  [1859, 'science', "Darwin publishes On the Origin of Species"],
  [1861, 'history', 'The American Civil War begins'],
  [1863, 'tech', 'The London Underground opens'],
  [1865, 'history', 'Abraham Lincoln is assassinated'],
  [1869, 'tech', 'The Suez Canal opens'],
  [1876, 'tech', 'Alexander Graham Bell patents the telephone'],
  [1877, 'sport', 'The first Wimbledon tennis championship'],
  [1879, 'tech', "Edison demonstrates his practical light bulb"],
  [1886, 'culture', 'The Statue of Liberty is dedicated'],
  [1886, 'culture', 'Coca-Cola is first sold'],
  [1889, 'culture', 'The Eiffel Tower opens'],
  [1891, 'sport', 'Basketball is invented'],
  [1893, 'history', 'New Zealand becomes the first country where women can vote'],
  [1895, 'science', 'Wilhelm Röntgen discovers X-rays'],
  [1895, 'culture', 'The Lumière brothers hold the first public film screening'],
  [1896, 'sport', 'The first modern Olympic Games, in Athens'],
  [1897, 'culture', 'Dracula is published'],
  [1901, 'science', 'The first Nobel Prizes are awarded'],
  [1903, 'tech', "The Wright brothers' first powered flight"],
  [1903, 'sport', 'The first Tour de France'],
  [1905, 'science', 'Einstein publishes special relativity'],
  [1908, 'tech', 'Ford introduces the Model T'],
  [1911, 'explore', 'Amundsen reaches the South Pole'],
  [1912, 'history', 'The Titanic sinks'],
  [1912, 'culture', 'The Oreo cookie is introduced'],
  [1914, 'history', 'World War I begins'],
  [1914, 'tech', 'The Panama Canal opens'],
  [1917, 'history', 'The Russian Revolution'],
  [1918, 'history', 'World War I ends'],
  [1920, 'history', 'Women win the right to vote across the US'],
  [1922, 'explore', "Tutankhamun's tomb is discovered"],
  [1923, 'culture', 'The Walt Disney Company is founded'],
  [1925, 'culture', 'The Great Gatsby is published'],
  [1927, 'explore', 'Lindbergh flies solo across the Atlantic'],
  [1927, 'culture', 'The Jazz Singer, the first feature-length "talkie"'],
  [1928, 'science', 'Alexander Fleming discovers penicillin'],
  [1928, 'culture', 'Mickey Mouse debuts in Steamboat Willie'],
  [1929, 'history', 'The Wall Street Crash'],
  [1930, 'sport', 'The first FIFA World Cup, in Uruguay'],
  [1931, 'culture', 'The Empire State Building opens'],
  [1936, 'sport', 'Jesse Owens wins four gold medals at the Berlin Olympics'],
  [1937, 'tech', 'The Golden Gate Bridge opens'],
  [1938, 'culture', 'Superman first appears in a comic book'],
  [1939, 'history', 'World War II begins'],
  [1939, 'culture', 'The Wizard of Oz is released'],
  [1940, 'culture', 'The first McDonald\'s restaurant opens'],
  [1941, 'culture', 'Mount Rushmore is completed'],
  [1945, 'history', 'World War II ends'],
  [1945, 'history', 'The United Nations is founded'],
  [1946, 'tech', 'ENIAC, an early general-purpose computer, is unveiled'],
  [1947, 'history', 'India gains independence'],
  [1948, 'history', "Britain's National Health Service is founded"],
  [1949, 'history', 'NATO is founded'],
  [1949, 'culture', "George Orwell's Nineteen Eighty-Four is published"],
  [1953, 'science', 'The double helix structure of DNA is described'],
  [1953, 'explore', 'Hillary and Tenzing reach the summit of Everest'],
  [1954, 'sport', 'Roger Bannister runs the first four-minute mile'],
  [1955, 'culture', 'Disneyland opens'],
  [1957, 'explore', 'Sputnik 1, the first artificial satellite, is launched'],
  [1958, 'explore', 'NASA is founded'],
  [1958, 'culture', 'The LEGO brick is patented'],
  [1959, 'culture', 'Barbie debuts'],
  [1960, 'science', 'The first working laser'],
  [1961, 'explore', 'Yuri Gagarin becomes the first human in space'],
  [1961, 'history', 'The Berlin Wall is built'],
  [1962, 'history', 'The Cuban Missile Crisis'],
  [1962, 'culture', 'Dr. No, the first James Bond film, is released'],
  [1963, 'history', 'Martin Luther King Jr. gives his "I Have a Dream" speech'],
  [1963, 'history', 'President John F. Kennedy is assassinated'],
  [1964, 'culture', 'The Beatles play on The Ed Sullivan Show'],
  [1966, 'culture', 'Star Trek first airs'],
  [1967, 'science', 'The first human heart transplant'],
  [1967, 'sport', 'The first Super Bowl'],
  [1969, 'explore', 'Apollo 11 lands on the Moon'],
  [1969, 'culture', 'The Woodstock festival'],
  [1970, 'history', 'The first Earth Day'],
  [1971, 'tech', 'The first email is sent'],
  [1971, 'culture', 'The first Starbucks opens, in Seattle'],
  [1972, 'tech', 'Pong is released'],
  [1973, 'tech', 'The first handheld mobile phone call'],
  [1973, 'culture', 'The Sydney Opera House opens'],
  [1974, 'culture', "The Rubik's Cube is invented"],
  [1975, 'tech', 'Microsoft is founded'],
  [1976, 'tech', 'Apple is founded'],
  [1977, 'culture', 'Star Wars is released'],
  [1978, 'science', 'Louise Brown, the first IVF baby, is born'],
  [1979, 'tech', 'Sony launches the Walkman'],
  [1980, 'tech', 'Pac-Man is released'],
  [1981, 'culture', 'MTV launches'],
  [1981, 'tech', 'The IBM Personal Computer is released'],
  [1982, 'culture', "Michael Jackson's Thriller is released"],
  [1984, 'tech', 'Apple launches the Macintosh'],
  [1984, 'tech', 'Tetris is created'],
  [1985, 'tech', 'Super Mario Bros. is released'],
  [1985, 'culture', 'The Live Aid concerts'],
  [1986, 'history', 'The Chernobyl disaster'],
  [1989, 'history', 'The Berlin Wall falls'],
  [1989, 'tech', 'Nintendo releases the Game Boy'],
  [1989, 'tech', 'Tim Berners-Lee proposes the World Wide Web'],
  [1990, 'explore', 'The Hubble Space Telescope is launched'],
  [1990, 'history', 'Nelson Mandela is released from prison'],
  [1991, 'history', 'The Soviet Union dissolves'],
  [1991, 'tech', 'The first website goes live'],
  [1993, 'culture', 'Jurassic Park is released'],
  [1994, 'tech', 'Amazon is founded'],
  [1994, 'tech', 'The Channel Tunnel opens'],
  [1994, 'tech', 'The PlayStation is released in Japan'],
  [1995, 'culture', 'Toy Story, the first fully computer-animated feature film'],
  [1996, 'science', 'Dolly the sheep, the first cloned mammal, is born'],
  [1996, 'tech', 'The Tamagotchi is released'],
  [1997, 'culture', "Harry Potter and the Philosopher's Stone is published"],
  [1997, 'tech', 'Deep Blue beats world chess champion Garry Kasparov'],
  [1998, 'tech', 'Google is founded'],
  [1999, 'culture', 'The Matrix is released'],
  [1999, 'history', 'The euro is introduced as a currency'],
  [2001, 'tech', 'Wikipedia is launched'],
  [2001, 'tech', 'Apple releases the iPod'],
  [2002, 'history', 'Euro coins and notes enter circulation'],
  [2003, 'science', 'The Human Genome Project is completed'],
  [2003, 'tech', 'Concorde makes its final flight'],
  [2004, 'tech', 'Facebook is launched'],
  [2005, 'tech', 'YouTube is launched'],
  [2006, 'tech', 'Twitter is launched'],
  [2006, 'science', 'Pluto is reclassified as a dwarf planet'],
  [2007, 'tech', 'The first iPhone is released'],
  [2008, 'tech', 'The Bitcoin whitepaper is published'],
  [2009, 'tech', 'Minecraft is first released to the public'],
  [2010, 'tech', 'Instagram is launched'],
  [2010, 'tech', 'Apple releases the first iPad'],
  [2012, 'science', 'The Higgs boson is discovered'],
  [2012, 'explore', 'The Curiosity rover lands on Mars'],
  [2014, 'explore', 'The Philae probe lands on a comet'],
  [2015, 'science', 'Gravitational waves are detected for the first time'],
  [2016, 'tech', 'Pokémon Go is released'],
  [2017, 'tech', 'The Nintendo Switch is released'],
  [2019, 'science', 'The first image of a black hole is published'],
  [2020, 'history', 'COVID-19 is declared a pandemic'],
  [2021, 'explore', 'The James Webb Space Telescope is launched'],
  [2022, 'tech', 'ChatGPT is released'],
]

// Ids come from the text, so a saved game still finds its events after rows move.
export const EVENTS: HistEvent[] = ROWS.map(([year, cat, text, approx]) => ({
  id: hashString(`${year}|${text}`).toString(36),
  year,
  cat,
  text,
  ...(approx ? { approx } : {}),
}))

export function formatYear(e: Pick<HistEvent, 'year' | 'approx'>): string {
  const y = e.year < 0 ? `${-e.year} BC` : `${e.year}`
  return e.approx ? `c. ${y}` : y
}
